services:

  serving:
    build: ./serving
    container_name: iris-api
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - ml-net

  redis:
    image: redis:7-alpine
    container_name: iris-cache
    volumes:
      - redis-data:/data
    networks:
      - ml-net

networks:
  ml-net:
    driver: bridge

volumes:
  redis-data: